name: crawler
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - flask=3.0.3
  - click=8.1.7
  - colorama=0.4.6
  - itsdangerous=2.2.0
  - jinja2=3.1.3
  - markupsafe=2.1.5
  - werkzeug=3.0.2
  - selenium=4.28.1
  - apscheduler=3.11.0
  - requests=2.32.3
  - httpx=0.28.1
  - pymongo=4.11
  - beautifulsoup4=4.13.1
  - pip
  - pip:
      - groq~=0.17.0
      - webdriver-manager